apptentive/apptentive-android

samples/apptentive-example/src/com/apptentive/android/example/ExampleActivity.java

This will fix the issue where the introductory dialog has the string "null" in place of the application name. It will also perform other Apptentive setup (as seen in the Apptentive.onStart method).

Use the Apptentive Activity Delegation mechanism

---

CHANGELOG.md
README.md
apptentive/src/main/AndroidManifest.xml
apptentive/src/main/java/com/apptentive/android/sdk/debug/ApptentiveAttachmentFileProvider.java
apptentive/src/main/java/com/apptentive/android/sdk/debug/LogBroadcastReceiver.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
samples/apptentive-example/build.gradle

* Fix a bug where the SDK can't be installed in multiple apps due to a hard-coded Provider authority string.

Release 4.1.1

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveViewActivity.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Fix a crash that was caused by a method being removed in the Android Support Library.

Release 4.1.2

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveViewActivity.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/MessageCenterFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/SurveyFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/view/survey/SurveyQuestionChoice.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/view/survey/TextSurveyQuestionView.java
apptentive/src/main/java/com/apptentive/android/sdk/module/messagecenter/ApptentiveToastNotificationManager.java
apptentive/src/main/java/com/apptentive/android/sdk/module/messagecenter/view/ApptentiveAvatarView.java
apptentive/src/main/java/com/apptentive/android/sdk/module/messagecenter/view/holder/GreetingHolder.java
apptentive/src/main/java/com/apptentive/android/sdk/module/messagecenter/view/holder/WhoCardHolder.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/java/com/apptentive/android/sdk/view/ApptentiveMaterialIndeterminateProgressBar.java

* Fix a NullPointerException crash while announcing accessibility events.

Release 4.1.3

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/Apptentive.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Fixed callback passing [issue](https://github.com/apptentive/apptentive-android/issues/141).

Release 5.0.1

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/view/survey/BaseSurveyQuestionView.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/view/survey/TextSurveyQuestionView.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Accessibility improvements for TalkBack.

Release 5.0.3

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/Apptentive.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveInstance.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveInternal.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveNullInstance.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveViewActivity.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/Conversation.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationDispatchTask.java
apptentive/src/main/java/com/apptentive/android/sdk/debug/Assert.java
apptentive/src/main/java/com/apptentive/android/sdk/migration/v4_0_0/VersionHistoryStoreMigrator.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/MessageCenterFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/messagecenter/MessageManager.java
apptentive/src/main/java/com/apptentive/android/sdk/module/messagecenter/MessagePollingWorker.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Nullsafe.java
apptentive/src/main/java/com/apptentive/android/sdk/util/ObjectUtils.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Util.java
tests/test-app/src/androidTest/java/com/apptentive/android/sdk/tests/ApptentiveTestCaseBase.java

* Fix a rare NullPointerException that occurs when Apptentive SDK activities are started without proper SDK initialization.

Release 5.0.4

---

CHANGELOG.md
README.md
apptentive/src/main/AndroidManifest.xml
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveConfiguration.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveInternal.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveLog.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Don't export ApptentiveAttachmentFileProvider.

Release 5.1.1

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveViewActivity.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Util.java

* Properly handle different app support library versions.

Release 5.1.2

---

.idea/codeStyles/codeStyleConfig.xml
CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/Apptentive.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveInternal.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveLogTag.java
apptentive/src/main/java/com/apptentive/android/sdk/model/Configuration.java
apptentive/src/main/java/com/apptentive/android/sdk/partners/apptimize/ApptentiveApptimize.java
apptentive/src/main/java/com/apptentive/android/sdk/partners/apptimize/ApptentiveApptimizeTestInfo.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Invocation.java
apptentive/src/main/java/com/apptentive/android/sdk/util/RuntimeUtils.java
apptentive/src/main/java/com/apptentive/android/sdk/util/StringUtils.java
build.gradle
settings.gradle

* Added support for Apptimize experiments.

Release 5.1.5

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/Apptentive.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Added `OnPreInteractionListener` to intercept interactions flow.

Release 5.2.0

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationLoadException.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationManager.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationMetadataLoadException.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/FileMessageStore.java
apptentive/src/main/java/com/apptentive/android/sdk/encryption/EncryptionException.java
apptentive/src/main/java/com/apptentive/android/sdk/encryption/EncryptionKey.java
apptentive/src/main/java/com/apptentive/android/sdk/encryption/Encryptor.java
apptentive/src/main/java/com/apptentive/android/sdk/encryption/SecurityManager.java
apptentive/src/main/java/com/apptentive/android/sdk/model/CompoundMessage.java
apptentive/src/main/java/com/apptentive/android/sdk/model/JsonPayload.java
apptentive/src/main/java/com/apptentive/android/sdk/model/Payload.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/ApptentiveDatabaseHelper.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/ApptentiveTaskManager.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/DatabaseMigrator.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/DatabaseMigratorV3.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Fixed SDK state restoration logic.
* Fixed 422 http errors.
* Fixed corrupted payloads if encryption key could not be resolved from the KeyStore.

Release 5.3.1

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/conversation/Conversation.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationManager.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/FileMessageStore.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Fixed encrypted message store for logged-in users.
* Fixed the bug which prevented users from logging-in back after a logout.

Release 5.3.2

---

.travis.yml
CHANGELOG.md
README.md
apptentive/build.gradle
apptentive/src/androidTest/java/com/apptentive/android/sdk/encryption/SecurityManagerTest.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveConfiguration.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveInternal.java
apptentive/src/main/java/com/apptentive/android/sdk/encryption/SecurityManager.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Util.java
build.gradle
gradle/wrapper/gradle-wrapper.properties
samples/apptentive-example/build.gradle
tests/test-app/build.gradle
tests/test-app/src/androidTest/java/com/apptentive/android/sdk/tests/ApptentiveTestCaseBase.java
tests/test-app/src/androidTest/java/com/apptentive/android/sdk/tests/misc/RandomTests.java

* Made encrypted storage configurable on the client.
* Updated SDK dependencies to Android-P

Release 5.4.0

---

.travis.yml
CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/Apptentive.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationMetadata.java
apptentive/src/main/java/com/apptentive/android/sdk/model/CommerceExtendedData.java
apptentive/src/main/java/com/apptentive/android/sdk/model/ExtendedData.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/AppRelease.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/EncryptedFileSerializer.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/EventRecord.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/FileSerializer.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/IntegrationConfigItem.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/OverrideSerialVersionUIDObjectInputStream.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/Sdk.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/VersionHistoryItem.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/test/java/com/apptentive/android/sdk/storage/ConversationDataTest.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

* Fixed loading conversation data when the build if obfuscated with R8.

Release 5.4.2

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveConfiguration.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveInternal.java
apptentive/src/main/java/com/apptentive/android/sdk/comm/ApptentiveHttpClient.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/Conversation.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationManager.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/MessageCenterFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/messagecenter/model/WhoCard.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/DeviceManager.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/DevicePayloadDiff.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/java/com/apptentive/android/sdk/util/StringUtils.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Util.java
build.gradle
samples/apptentive-example/build.gradle

* Made Android ID collection optional on pre-Oreo targets.
* Fixed "Who" card in the Message Center.

Release 5.4.3

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/encryption/SecurityManager.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

Release 5.4.4

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/ApptentiveBaseFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Fixed Fragment crash while using `androidx.appcompat:appcompat:1.1.+` dependency.

Release 5.4.5

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/ApptentiveBaseFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/MessageCenterFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/SurveyFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Fixed Fragment crash while using `androidx.navigation:navigation-fragment-ktx` dependency.

Release 5.4.6

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveViewActivity.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Fixed crash while configuration changes.

Release 5.4.7

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveConfiguration.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveInstance.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveInternal.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveNullInstance.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/SurveyFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/model/SurveyInteraction.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/model/TermsAndConditions.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/java/com/apptentive/android/sdk/util/StringUtils.java
apptentive/src/main/res/layout/apptentive_survey.xml

* Add a configuration property to display terms and conditions.

Release 5.5.1

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/SurveyFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/res/layout/apptentive_survey.xml

* Fix potential NPE when presenting a survey without terms and conditions.

Release 5.5.2

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/SurveyFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/view/survey/BaseSurveyQuestionView.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/view/survey/RangeSurveyQuestionView.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/view/survey/SurveyQuestionView.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Improve Accessibility in Surveys for TalkBack users.

Release 5.5.3

---

CHANGELOG.md
README.md
apptentive/build.gradle
apptentive/src/main/java/com/apptentive/android/sdk/storage/DeviceManager.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

Release 5.5.4

---

CHANGELOG.md
README.md
apptentive/build.gradle
apptentive/src/androidTest/java/com/apptentive/android/sdk/module/engagement/InAppRatingDialogInteractionLauncherTest.java
apptentive/src/androidTest/java/com/apptentive/android/sdk/module/engagement/InteractionLauncherTest.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveLog.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveLogTag.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/Conversation.java
apptentive/src/main/java/com/apptentive/android/sdk/external/DefaultEngagement.java
apptentive/src/main/java/com/apptentive/android/sdk/external/DefaultInAppReviewManagerFactory.java
apptentive/src/main/java/com/apptentive/android/sdk/external/Engagement.java
apptentive/src/main/java/com/apptentive/android/sdk/external/GooglePlayReviewManager.java
apptentive/src/main/java/com/apptentive/android/sdk/external/InAppReviewListener.java
apptentive/src/main/java/com/apptentive/android/sdk/external/InAppReviewManager.java
apptentive/src/main/java/com/apptentive/android/sdk/external/InAppReviewManagerFactory.java
apptentive/src/main/java/com/apptentive/android/sdk/external/UnsupportedReviewManager.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/ActivityInteractionLauncher.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/DefaultInteractionLauncherFactory.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/EngagementModule.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/InAppRatingDialogInteractionLauncher.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/InteractionLauncher.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/NotificationInteractionLauncher.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/model/InAppRatingDialogInteraction.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/model/Interaction.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Callback.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Google Play In-App Review support.

Release 5.6.0

---

CHANGELOG.md
README.md
apptentive/consumer-proguard-rules.pro
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationMetadata.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Google Play Core library ProGuard fixes.

Release 5.6.2

---

CHANGELOG.md
README.md
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationManager.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/AppRelease.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/Device.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/Sdk.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Fixes a race condition where information about the SDK and app was failing to be recorded.

Release 5.6.3

---

.github/CODEOWNERS
CHANGELOG.md
README.md
apptentive/src/androidTest/java/com/apptentive/android/sdk/module/engagement/logic/DefaultRandomPercentProviderTest.java
apptentive/src/androidTest/java/com/apptentive/android/sdk/module/engagement/logic/FieldManagerTest.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationProxy.java
apptentive/src/main/java/com/apptentive/android/sdk/debug/LogMonitor.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/NoteFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/model/Targets.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/logic/DefaultRandomPercentProvider.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/logic/FieldManager.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/logic/RandomPercentProvider.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/notification/NoteInteractionNotificationAdapter.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Util.java
build.gradle

* Prevent Clipboard Notifications for Release builds in Android 12.
* Replace JCenter with Maven Central.

Release 5.6.4

---

CHANGELOG.md
README.md
apptentive/src/androidTest/java/com/apptentive/android/sdk/module/engagement/logic/DefaultRandomPercentProviderTest.java
apptentive/src/androidTest/java/com/apptentive/android/sdk/module/engagement/logic/FieldManagerTest.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationProxy.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/NoteFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/model/Targets.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/logic/DefaultRandomPercentProvider.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/logic/FieldManager.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/logic/RandomPercentProvider.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/notification/NoteInteractionNotificationAdapter.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java

* Add the ability to randomly target a percentage of customers.

Release 5.7.0

---

.github/CODEOWNERS
.travis.yml
CHANGELOG.md
README.md
apptentive/build.gradle
apptentive/src/main/AndroidManifest.xml
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveConfiguration.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveInternal.java
apptentive/src/main/java/com/apptentive/android/sdk/ApptentiveNotifications.java
apptentive/src/main/java/com/apptentive/android/sdk/conversation/ConversationManager.java
apptentive/src/main/java/com/apptentive/android/sdk/debug/LogBroadcastReceiver.java
apptentive/src/main/java/com/apptentive/android/sdk/debug/TroubleshootingNotificationBuilder.java
apptentive/src/main/java/com/apptentive/android/sdk/module/engagement/interaction/fragment/NoteFragment.java
apptentive/src/main/java/com/apptentive/android/sdk/storage/DeviceManager.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Constants.java
apptentive/src/main/java/com/apptentive/android/sdk/util/StringUtils.java
apptentive/src/main/java/com/apptentive/android/sdk/util/ThrottleUtils.java
apptentive/src/main/java/com/apptentive/android/sdk/util/Util.java
apptentive/src/test/java/com/apptentive/android/sdk/storage/ConversationDataTest.java
build.gradle
samples/apptentive-example/build.gradle
samples/apptentive-example/src/main/AndroidManifest.xml
tests/test-app/build.gradle
tests/test-app/src/androidTest/java/com/apptentive/android/sdk/tests/module/engagement/DataObjectQueryTest.java
tests/test-app/src/main/AndroidManifest.xml

* Fix conversation deserialization issue with conversation reset & throttle once per SDK version
* Register lifecycle callback on the main thread
* Remove all references of AndroidID
* Add troubleshooting mode for Android 12+ with a Apptentive certificate
* Support long texts for alert dialog buttons

Release 5.8.3
